# Generated by Django 2.2.4 on 2021-03-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_comment_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
